// src/services/geminiService.ts

// --- MOCK AI SERVICE ---
// This file simulates AI responses so the app runs without an API Key.

export const generateReportFromNaturalLanguage = async (prompt: string, type: string) => {
    console.log(`[Mock AI] Generating report for: ${prompt}`);
    return new Promise<any>((resolve) => {
        setTimeout(() => {
            resolve({
                wasFire: prompt.toLowerCase().includes('fire'),
                wasInjuryOrIllness: prompt.toLowerCase().includes('hurt') || prompt.toLowerCase().includes('injury'),
                wasEnvironmentImpacted: prompt.toLowerCase().includes('spill'),
                incidentCodes: ['SFTY', 'MOCK'],
                evidenceSuggestedItems: ['Photo of the area', 'Witness statement', 'CCTV Footage'],
                evidenceSummary: 'AI Analysis: Based on the description, this appears to be a standard safety incident. Please verify details.'
            });
        }, 1000);
    });
};

export const generateSafetyReport = async (prompt: string) => {
    return `## AI Safety Assessment\n\n**Subject:** ${prompt}\n\nThis is a simulated AI report. To get real insights, you will need to configure your Google Gemini API key later.\n\n**Recommendations:**\n1. Review safety protocols.\n2. Ensure PPE compliance.\n3. Conduct a toolbox talk.`;
};

export const generateAiRiskForecast = async () => {
    return {
        risk_level: 'Medium',
        summary: 'Moderate risk detected due to high temperatures and ongoing lifting operations.',
        recommendations: ['Enforce hydration breaks', 'Check lifting gear certification', 'Monitor wind speeds']
    };
};

export const generateRamsContent = async (prompt: string) => {
    return {
        overview: `Method Statement for: ${prompt}\n\n1. Ensure work area is barricaded.\n2. Verify all permits are active.\n3. Conduct TBT before start.`,
        competence: "All personnel must hold valid cards and specific training for this task.",
        sequence_of_operations: [
            {
                step_no: 1,
                description: "Site Preparation",
                hazards: [{ id: "h1", description: "Slips, Trips, Falls" }],
                controls: [{ id: "c1", description: "Good housekeeping", hierarchy: "administrative" }],
                risk_before: { severity: 3, likelihood: 3 },
                risk_after: { severity: 3, likelihood: 1 }
            }
        ],
        emergency_arrangements: "In case of emergency, stop work immediately and proceed to assembly point A."
    };
};

export const generateTbtContent = async (title: string) => {
    return {
        summary: `Today we are discussing ${title}. Please pay attention to the following key points.`,
        hazards: ["Unexpected movement", "Falling objects", "Pinch points"],
        controls: ["Stay within walkways", "Wear helmet and gloves", "Maintain eye contact with operator"],
        questions: ["What is the main hazard here?", "Who is the responsible supervisor?"]
    };
};

export const generateCourseContent = async (title: string) => {
    return {
        syllabus: `# Course: ${title}\n\n## Module 1: Introduction\n- Overview of ${title}\n- Legal requirements\n\n## Module 2: Hazards\n- Identifying risks\n- Control measures\n\n## Module 3: Practical\n- Hands-on demonstration`,
        learning_objectives: ["Understand key risks", "Demonstrate safe use of equipment", "Know emergency procedures"]
    };
};

export const generateReportSummary = async (json: string) => {
    return "This is a summary of the incident report generated by the mock AI service. It highlights key areas such as root cause and immediate actions taken.";
};

export const generateCertificationInsight = async (profile: any) => {
    return {
        nextLevelRecommendation: "Focus on leading more safety inspections to reach the 'Advanced' level.",
        missingItems: ["Lead 5 TBTs", "Complete 'Advanced Risk Assessment' course"]
    };
};

export const translateText = async (text: string, lang: string) => {
    return `[Translated to ${lang}]: ${text}`;
};